#!/bin/sh
#
# This material is based upon work supported by the Defense Advanced
# Research Projects Agency under Contract No. N66001-11-C-4017.
#
# Copyright 2014 - Raytheon BBN Technologies Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

# Assumes that we're running on Ubuntu, 64-bit, and NSS was compiled
# with either DBG or OPT.
#
# This must be run inside the packaging directory  The paths used
# are relative to the packaging directory.


BUILDTYPE_DBG=Linux3.13_x86_64_glibc_PTH_64_DBG.OBJ
BUILDTYPE_OPT=Linux3.13_x86_64_glibc_PTH_64_OPT.OBJ

CERTUTILDIR=../nss/nss-3.13.3/mozilla/security/nss/cmd/certutil

CERTDB=../test/auth/certdb

ls -l $CERTUTILDIR/$BUILDTYPE_DBG

if [ -x "$CERTUTILDIR/$BUILDTYPE_DBG/certutil" ]; then
    CERTUTIL="$CERTUTILDIR/$BUILDTYPE_DBG/certutil"
elif [ -x "$CERTUTILDIR/$BUILDTYPE_OPT/certutil" ]; then
    CERTUTIL="$CERTUTILDIR/$BUILDTYPE_OPT/certutil"
else
    echo "ERROR: no certutil found"
    exit 1
fi

mkdir -p $CERTDB
rm -f $CERTDB/cert8.db $CERTDB/key3.db $CERTDB/secmod.db

$CERTUTIL -d $CERTDB -A -t "CT,c,c" -n curveball \
	-i ../CA/CA/CURVEBALL_CA.pem

exit $?
