#!/bin/bash
#
# This material is based upon work supported by the Defense Advanced
# Research Projects Agency under Contract No. N66001-11-C-4017.
#
# Copyright 2014 - Raytheon BBN Technologies Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

# Create a VERSION name to use for the current version.
# This must be a string that can be used as a Debian package version
# string and a Python egg version string, and export it.
#
# The Python egg version restrictions are the most restrictive across
# different platforms: three, two, or one 15-bit integers, separated by
# periods.
#
# The convention is to use the date in form YYYY.MM.DD, which
# satisfies the current restrictions (until several tens of thousands
# of years from now), but almost anything can be used.

/bin/date +"%Y.%m.%d"
