#!/bin/bash
#
# This material is based upon work supported by the Defense Advanced
# Research Projects Agency under Contract No. N66001-11-C-4017.
#
# Copyright 2014 - Raytheon BBN Technologies Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

# On 12.04, the libc that danted requires is missing.
# Make a symlink to replace it, but only on 12.04.

# If lsb_release doesn't exist, then we're certainly not on Ubuntu 12.04,
# because we're not on Ubuntu of any recent vintage.
#

if [ ! -x /usr/bin/lsb_release ]; then
    echo "Nothing to be done..."
else
    PLATFORM="$(/usr/bin/arch)-linux-gnu"

    RELEASE=$(/usr/bin/lsb_release -rs)

    case "${RELEASE}" in
	10.04)
	    # echo "Nothing to do for 10.04"
	    ;;
	12.04)
	    echo "Adding symlink needed for 12.04..."
	    sudo rm -f /lib/${PLATFORM}/libc.so
	    sudo ln -s /lib/${PLATFORM}/libc.so.6 /lib/${PLATFORM}/libc.so
	    ;;
	*)
	    echo "Unrecognized release"
	    ;;
    esac
fi

exit 0

