#!/bin/bash 
#
# This material is based upon work supported by the Defense Advanced
# Research Projects Agency under Contract No. N66001-11-C-4017.
#
# Copyright 2014 - Raytheon BBN Technologies Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.


# Find this node's name, copy its private node key and certificate to the
# correct place.
#
# Input: full path to directory containing the certificate and key file
#        default: /opt/curveball/auth/nodes

# logging/diagnostic functions
script_name=$(basename "$0")
log() { printf '%s: %s\n' "${script_name}" "$*"; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
usage_fatal() { error "$*"; usage >&2; exit 1; }

usage() { 
    printf '%s %s\n' "${script_name}"  "[directory containing certificate and key files]"; 
    exit 1
}


if [ $(id -u) -ne 0 ]; then
    fatal "must be run as root"
fi

if [ $# -eq 0 ]; then
    log "using default location of node certs"
    CB_CERTDIR="/opt/curveball/auth/nodes"
fi

if [ $# -eq 1 ]; then
    case $1 in 
	--help|-h)
	    usage
	    ;;
	*)
	    CB_CERTDIR="$1"
    esac
fi

if [ $# -gt 1 ]; then
    usage_fatal "Wrong number of arguments"
fi

#echo "${CA_CERTFILE}"


if [ ! -d "${CB_CERTDIR}" ]; then
    fatal "${CB_CERTDIR} not found "
fi

do_install_node_cert() {

    SHORTNAME=$(/bin/hostname | /bin/sed -e 's/\..*//')

    #log ${CB_CERTDIR}/${SHORTNAME}.pem

    if [ ! -f "${CB_CERTDIR}/${SHORTNAME}.pem" ]; then
	fatal " ${CB_CERTDIR}/${SHORTNAME}.pem not found"
    fi

    if  [ ! -f "${CB_CERTDIR}/${SHORTNAME}.key" ]; then
	fatal "${CB_CERTDIR}/${SHORTNAME}.key not found"
    fi

    log "COPYING CERT AND KEY FOR ${SHORTNAME} TO /etc/ssl/certs AND /etc/ssl/private"

    /bin/cp "${CB_CERTDIR}/${SHORTNAME}.pem" /etc/ssl/certs/
    /bin/chmod 0644 "/etc/ssl/certs/${SHORTNAME}.pem"

    /bin/cp "${CB_CERTDIR}/${SHORTNAME}.key" /etc/ssl/private/
    /bin/chmod 0640 "/etc/ssl/private/${SHORTNAME}.key"

    # This group doesn't appear to exist on EARS.
    # /bin/chgrp ssl-cert "/etc/ssl/private/${SHORTNAME}.key"
}

do_install_node_cert
