#!/bin/sh
#
# This material is based upon work supported by the Defense Advanced
# Research Projects Agency under Contract No. N66001-11-C-4017.
#
# Copyright 2014 - Raytheon BBN Technologies Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.


# Pushes the "bad decoy host" lists out to the DRs.
#
# Currently only tested regularly with exactly one DR and DP.
#
# You should think seriously about setting up your ssh keys and/or
# ssh-agent before running this, because otherwise you're going to
# get very tired of typing your password/passphrase over and over.

# logging/diagnostic functions
script_name=$(basename "$0")
log() { printf '%s: %s\n' "${script_name}" "$*"; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
usage_fatal() { error "$*"; usage >&2; exit 1; }

usage() {
    printf "Usage: %s [SRCDIR]\n" ${0}
}

RSYNC=/usr/bin/rsync
SSH=/usr/bin/ssh

BDH_SUFFIX=bdh

DR_BDH_DEST_DIR=/tmp/dr/baddh

SCRIPTDIR=$(/bin/readlink -f $(/usr/bin/dirname $(/usr/bin/which "$0")))
CLEANUP=${SCRIPTDIR}/cb-noc-cleanup

node_exists() {
    # echo "NODE $1"

    nodename="$1"
    ping -q -c 1 -w 1 ${nodename} > /dev/null 2>&1
    res=$?
    return $res
}

# assume that we're using the same login locally as on the DR.
#
DR_USER=${USER}

push_dr() {

    dr=$1

    node_exists "${dr}"
    if [ $? -eq 0 ]; then

	echo "PUSHING TO DR ${dr}:${DR_BDH_DEST_DIR}"

	${SSH} ${DR_USER}@${dr} \
		"/bin/sh -c 'mkdir -p -m 0755 ${DR_BDH_DEST_DIR}'"
	${RSYNC} -r --delay-updates ${SRCDIR}/*.${BDH_SUFFIX} \
		${DR_USER}@${dr}:${DR_BDH_DEST_DIR}/

	${SSH} "${DR_USER}@${dr}" "${CLEANUP}" "${DR_BDH_DEST_DIR}"

	if [ $? -ne 0 ]; then
	    echo "ERROR synching with DR ${dr}"
	    rc=1
	    exit 1
	fi
    # else 
	# echo SKIPPING MISSING DR $nodename
    fi
}

if [ $# -gt 1 ]; then
    usage_fatal "Bad commandline"
fi

if [ $# -eq 1 ]; then
    SRCDIR=${1}
else
    SRCDIR='out'
fi

echo using SRCDIR ${SRCDIR} # debugging

# There might be nothing to push; test first.
# Otherwise rsync will be confused when
# *.${BDH_SUFFIX} expands to nothing.
# 
# BUG: if the files are deleted between this test
# and their use below, the behavior is undefined.
# A classic TOCTOU bug.
#
if ! /usr/bin/test -n \
	"$(find ${SRCDIR} -maxdepth 1 -name \
		'cb-g*'.${BDH_SUFFIX} -print -quit)"; then
    echo "No .${BDH_SUFFIX} files to push"
    exit 0
fi

# These are the current node suffixes, but this list must be
# kept up-to-date.
#
onedig="0 1 2 3 4 5 6 7 8 9"
twodig=""

for digit1 in $onedig; do
    for digit0 in $onedig; do
	twodig="$twodig $digit1$digit0"
    done
done

NAME_SUFFIXES="$onedig $twodig"

rc=0

for name in dr; do
    push_dr "$name"

    for suffix in ${NAME_SUFFIXES}; do
	nodename="${name}${suffix}"
	push_dr "$nodename"
    done
done

# Cleanup the scratch directory
#
if [ -x "${CLEANUP}" ]; then
    "${CLEANUP}" "${SRCDIR}"
fi

exit $rc
