#!/bin/sh
#
# This material is based upon work supported by the Defense Advanced
# Research Projects Agency under Contract No. N66001-11-C-4017.
#
# Copyright 2014 - Raytheon BBN Technologies Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.


# Pushes generated sentinel list files and sentinel Bloom filter files
# out to the DPs and DRs.  Useful only of local CORE instances;
# assumes that all the hosts share a file system.
#

SCRIPTNAME=$(/usr/bin/basename "$0")
SCRIPTDIR=$(/bin/readlink -f $(/usr/bin/dirname $(/usr/bin/which "$0")))

CP=/bin/cp
MKDIR=/bin/mkdir
CLEANUP=${SCRIPTDIR}/cb-noc-cleanup

SENT_SUFFIX=sent
SENT_BF_SUFFIX=sbf
SENT_DH_SUFFIX=dhexp

DP_DEST_DIR=/tmp/dp/sentinels
DR_DEST_DIR=/tmp/dr/bloomfilters

if [ $# != 1 ]; then
  echo "Error: no source directory given"
  exit 1
fi

SRCDIR=${1}

if [ ! -d ${SRCDIR} ]; then
  echo "ERROR: source directory ${SRCDIR} not present"
  exit 1
fi

${MKDIR} -p -m 0755 ${DP_DEST_DIR}
if [ $? -ne 0 ]; then
  echo "ERROR creating ${DR_DEST_DIR}"
  exit 1
fi

${MKDIR} -p -m 0755 ${DR_DEST_DIR}
if [ $? -ne 0 ]; then
  echo "ERROR creating ${DR_DEST_DIR}"
  exit 1
fi

${CP} ${SRCDIR}/*.${SENT_SUFFIX} ${DP_DEST_DIR}/
if [ $? -ne 0 ]; then
  echo "ERROR synching .$SENT_SUFFIX files with DP"
  exit 1
fi

# We don't do BitTorrent DH sentinels in this release
#
# ${CP} ${SRCDIR}/*.${SENT_DH_SUFFIX} ${DP_DEST_DIR}/
# if [ $? -ne 0 ]; then
#   echo "ERROR synching .$SENT_DH_SUFFIX files with DP"
#   exit 1
# fi

${CP} ${SRCDIR}/*.${SENT_BF_SUFFIX} ${DR_DEST_DIR}/
if [ $? -ne 0 ]; then
  echo "ERROR synching with DR"
  exit 1
fi

# Remove any old, out-of-date files
#
if [ -x "${CLEANUP}" ]; then
    "${CLEANUP}" "${DP_DEST_DIR}" "${DR_DEST_DIR}" "${SRCDIR}"
else
    echo "Warning: the cleaning script is missing"
fi

exit 0
